### ISSUE TITLE
Did you have test.py

### ISSUE THREAD

**Issue by 1297299883** [jleinonen/downscaling-rnn-gan#5] opened 2020-05-31 13:07 UTC
Did you have test.py?  I need to run test.py file to eval...   
If you have this file ,please send to me ,thank you,

**Comment by jleinonen** [comment] 2020-06-18 16:14
I'm not sure why there would be a test.py file included... Closing this for now since the issue is rather old.

**Closed as completed by jleinonen** 2020-06-18 16:14 UTC
